language: c
compiler:
  - gcc
  - clang
before_install: sudo apt-get -y update
install:
  - sudo apt-get -y install libfcgi-dev
  - sudo apt-get -y install libjson-c-dev || sudo apt-get -y install libjson0-dev
script: make

