language: c
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get -y update
  - sudo ln -sf bash /bin/sh
install:
  - pushd ~
  - wget "https://github.com/json-c/json-c/archive/json-c-0.12-20140410.tar.gz" -O - | tar xz
  - cd json-*
  - ./configure --prefix=/usr
  - make
  - sudo make install
  - popd
script: make

